kind: pipeline
name: build
steps:
  - name: buildah
    image: quay.io/buildah/stable:v1.11.2
    environment:
      DOCKER_USERNAME:
        from_secret: docker-username
      DOCKER_PASSWORD:
        from_secret: docker-password
      BUILDAH_STARTED_IN_USERNS: ''
      BUILDAH_ISOLATION: 'chroot'
    commands:
      - 'cd /drone/src'
      - 'buildah bud -t inspirehep/disambiguation:{DRONE_COMMIT_SHA} .'
      - 'buildah push --creds ${DOCKER_USERNAME}:${DOCKER_PASSWORD} inspirehep/disambiguation:{DRONE_COMMIT_SHA} docker://inspirehep/disambiguation:{DRONE_COMMIT_SHA}'

---
kind: pipeline
name: test
clone:
  disable: true
depends_on:
  - build
steps:
  - name: flake8
    image: 'inspirehep/disambiguation:${DRONE_COMMIT_SHA}'
    commands:
      - cd /opt/disambiguation
      - poetry run flake8
  - name: pytest
    image: 'inspirehep/disambiguation:${DRONE_COMMIT_SHA}'
    commands:
      - cd /opt/disambiguation
      - poetry run py.test tests
